#!/bin/bash
# This script checks for Core dumps, if found it loads them up, performs
# a backtrace and send's an email

set -e
(
	cd /opt/gamecq/

	# Find all cores even in subdirectories. The -o option means OR
	CORES="$(find . -type d -name 'cores' -prune -o -type f -name 'core.*')"
	for CORE_NAME in $CORES
	do

	if [ -f $CORE_NAME ]; then

	echo "Processing core $CORE_NAME..."

	DIR_NAME="$(dirname $CORE_NAME)"
	EXE_NAME=$DIR_NAME/$(gdb -q -c $CORE_NAME -batch 2> /dev/null | grep 'Core was generated by' | sed -e 's/^Core was generated by `\(.*\)'\''./\1/')
		
	echo "Dumping backtrace for $EXE_NAME ($CORE_NAME)..." > /tmp/CoreAlert
	gdb $EXE_NAME -q -batch -x CoreCommands -c $CORE_NAME >> /tmp/CoreAlert 2> /dev/null 

	# Send emails containing the backraces
	mail -s "Core Alert $EXE_NAME ($CORE_NAME)" rlyle@palestar.com backslash@palestar.com < /tmp/CoreAlert

	# Move the core into another directory
	mkdir -p /opt/gamecq/cores/
	mv -f $CORE_NAME /opt/gamecq/cores/
	 
	fi
	done

) 200>/tmp/CoreWatchCron.lock

