//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GCQL.rc
//
#define IDR_RT_MANIFEST1                1
#define IDD_ABOUTBOX                    100
#define IDS_MAIN_TOOLBAR                101
#define IDS_FRIEND_TOOLBAR              102
#define IDD_OPTIONS_GENERAL             106
#define CG_IDD_PROGRESS                 107
#define CG_IDS_PROGRESS_CAPTION         108
#define IDD_FINDUSER                    109
#define IDR_MAINFRAME                   128
#define IDR_GCQLTYPE                    129
#define IDR_POPUP_PLAYER                129
#define IDD_PROFILE                     130
#define IDR_POPUP_TOOLBAR               131
#define IDR_WAVE1                       131
#define IDR_EMPTY_HTML                  131
#define IDD_PROFILE_FIELD               131
#define IDW_CHAT01                      131
#define IDR_POPUP_PLAYERM               132
#define IDD_LOGIN                       135
#define IDI_AVATAR                      136
#define IDI_DOWN                        146
#define IDD_ROOMS                       147
#define IDI_UP                          147
#define IDD_CREATE_ROOM                 148
#define IDI_RIGHT                       148
#define IDD_FTP_UPDATE                  149
#define IDB_CAPTION                     150
#define IDB_TOOLBAR256                  151
#define IDB_TOOLBARCOLD256              152
#define IDD_EULA                        152
#define IDR_EULA                        153
#define IDR_USERBAR                     153
#define IDR_NAVBAR                      155
#define IDR_CHATBAR                     157
#define IDB_ONLINE                      158
#define IDB_OFFLINE                     159
#define IDD_NEWLOGIN                    163
#define IDD_SELECTGAME                  164
#define IDI_GAME                        165
#define IDI_GAME_DEMO                   165
#define IDI_ROOM                        166
#define IDI_FRIENDS                     167
#define IDI_CLAN                        168
#define IDI_CLANS                       169
#define IDI_GAMES                       170
#define IDI_ROOMS                       171
#define IDI_FRIEND                      172
#define IDI_AVATAR_MOD                  173
#define IDI_AVATAR_ADMIN                174
#define IDR_FRIEND_ALERT                174
#define IDW_MESSAGE01                   174
#define IDI_FRIEND_OFFLINE              175
#define IDR_POPUP_GAME                  176
#define IDR_POPUP_SERVER                176
#define IDR_POPUP_FRIEND                177
#define IDD_MESSAGE                     180
#define IDI_MESSAGE                     181
#define IDI_CANCEL                      182
#define IDD_OPTIONS                     183
#define IDI_AVATAR_AWAY                 183
#define IDD_EMOTION_EDIT                184
#define IDI_GAME_RELEASE                184
#define IDD_CHANGE_PASSWORD             185
#define IDI_GAME_BETA                   185
#define IDR_GAMEBAR                     190
#define IDR_CACHEBAR                    190
#define IDR_TOPCHATBAR                  191
#define IDR_SERVERBAR                   192
#define IDD_CHANGE_NAME                 194
#define IDD_IGNORES                     195
#define IDI_MACHINE                     197
#define IDI_PROCESS_STOPPED             198
#define IDI_PROCESS_ACTIVE              199
#define IDR_POPUP_PROCESS               200
#define IDI_AVATAR_HIDDEN               200
#define IDI_MUTED                       201
#define IDR_INCOMING_MSG                202
#define IDI_PMESSAGE                    202
#define IDI_PROGRAM                     203
#define IDI_AVATAR_DEV                  204
#define IDR_POPUP_FINDUSER              205
#define IDD_ROOM_PASSWORD               206
#define IDR_POPUP_MANAGEUSERS           208
#define IDR_POPUP_GAMECQ                218
#define IDI_AVATAR_INGAME               222
#define IDI_AVATAR1                     223
#define IDI_AVATAR_SUB                  223
#define IDC_BUTTON1                     1003
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_BUTTON2                     1004
#define IDC_EDIT2                       1004
#define IDC_CHECK1                      1005
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_EDIT3                       1005
#define IDC_BUTTON5                     1005
#define IDC_CHAT_EDIT                   1006
#define IDC_EDIT6                       1006
#define IDC_BUTTON6                     1006
#define IDC_CHECK9                      1006
#define IDC_EDIT7                       1007
#define IDC_BUTTON7                     1007
#define IDC_CHECK10                     1007
#define IDC_ENABLE_WORD_FILTER          1007
#define IDC_BUTTON8                     1008
#define IDC_COMBO1                      1012
#define IDC_CHECK4                      1013
#define IDC_CHECK2                      1014
#define IDC_CHECK3                      1015
#define IDC_CHECK6                      1016
#define IDC_BUTTON3                     1017
#define IDC_CHECK7                      1017
#define IDC_LIST1                       1018
#define IDC_CHECK11                     1018
#define IDC_EDIT1                       1019
#define IDC_CHECK8                      1019
#define IDC_EDIT4                       1020
#define IDC_EULA                        1021
#define IDC_EDIT5                       1021
#define IDC_EDIT8                       1022
#define IDC_CHAT_HISTORY                1026
#define IDC_COMPANY_URL                 1041
#define IDC_TO                          1043
#define IDC_CHECK5                      1044
#define IDC_BUTTON4                     1045
#define IDC_CHATSPLIT                   1046
#define IDC_LIST2                       1050
#define IDC_BUTTON9                     1051
#define IDC_BUTTON10                    1052
#define IDC_BUTTON11                    1053
#define IDC_BUTTON12                    1054
#define IDC_BUTTON13                    1055
#define IDC_BUTTON14                    1056
#define IDC_BUTTON15                    1057
#define IDC_BUTTON16                    1058
#define IDC_BUTTON17                    1059
#define IDC_BUTTON18                    1060
#define IDC_CPU                         1062
#define IDC_MEMORY                      1063
#define IDC_STATIC_CHECKBOX             1064
#define IDC_HIDDEN_CHECKBOX             1065
#define IDC_MOD_CHECKBOX                1066
#define IDC_COPYWRITE                   1068
#define IDC_PROGRESS1                   4000
#define IDD_CLIENT_UPDATE               4000
#define IDC_PROGRESS2                   4001
#define IDD_CHANGE_EMAIL                4001
#define IDC_FILESTATUS                  4002
#define IDC_STATUS                      4003
#define IDD_OPTIONS_EMOTS               4004
#define IDD_OPTIONS_COLORS              4005
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_CAPTIONBAR              32816
#define ID_NAVIGATION_REFRESH           32822
#define ID_NAVIGATION_BACK              32823
#define ID_NAVIGATION_FORWARD           32824
#define ID_CLAN_JOINCLAN                32829
#define ID_CLAN_CREATECLAN              32830
#define ID_GAME_JOINGAME                32832
#define ID_CHAT_SENDCHAT                32835
#define ID_FRIENDS_ADDFRIEND            32838
#define ID_FRIENDS_DELETEFRIEND         32839
#define ID_CHAT_EDIT                    32852
#define ID_ADMIN_BANUNBANUSERS          32873
#define ID_PLAYER_SEND                  32873
#define ID_ADMIN_SUBMITNEWS             32874
#define ID_USER_CHANGEUSERNAME          32876
#define ID_USER_CHANGEEMAIL             32877
#define ID_ADMIN_EDITUSERS              32889
#define ID_VIEW_OPTIONS                 32890
#define ID_CHAT_COLOR                   32891
#define ID_VIEW_CONTENT                 32893
#define ID_VIEW_PLAYERS                 32894
#define ID_USER_FRIENDS_VIEW            32897
#define ID_USER_FRIENDS_REFRESH         32898
#define ID_CLAN_VIEW                    32899
#define ID_CLAN_REFRESH                 32900
#define ID_GAMECQ_SAVECHAT              32901
#define ID_CONNECT                      32902
#define ID_GAME_CONNECT                 32904
#define ID_GAME_REFRESH                 32905
#define ID_PLAYER_ADDFRIEND             32906
#define ID_PLAYER_ADDIGNORE             32907
#define ID_PLAYER_BAN                   32908
#define ID_PLAYER_WHISPER               32910
#define ID_PLAYER_WHO                   32911
#define ID_PLAYER_CLAP                  32912
#define ID_PLAYER_WINK                  32914
#define ID_PLAYER_LAUGH                 32916
#define ID_PLAYER_GIGGLE                32917
#define ID_PLAYER_NOD                   32918
#define ID_PLAYER_WAVE                  32919
#define ID_PLAYER_HUG                   32920
#define ID_PLAYER_KISS                  32921
#define ID_FRIEND_SENDMESSAGE           32922
#define ID_FRIEND_JOIN                  32923
#define ID_FRIEND_INVITE                32924
#define ID_FRIEND_REMOVE                32925
#define ID_PLAYER_EDIT                  32926
#define ID_HELP_MANUALONLINE            32927
#define ID_ADMIN_BROADCAST              32928
#define ID_GAMEBAR_PLAY                 32934
#define ID_GAMEBAR_HOME                 32938
#define ID_GAMEBAR_DOWNLOAD             32939
#define ID_GAMEBAR_ROOMS                32941
#define ID_GAMECQ_PLAY                  32942
#define ID_GAMECQ_DOWNLOAD              32943
#define ID_GAMECQ_HOME                  32944
#define ID_GAMEBAR_CREATE_ROOM          32945
#define ID_GAMEBAR_FRIENDS              32947
#define ID_GAMEBAR_CLAN                 32948
#define ID_GAMEBAR_CLANS                32949
#define ID_GAMEBAR_LOBBY                32950
#define ID_GAMEBAR_PROFILE              32951
#define ID_VIEW_NAVIGATIONBAR           32952
#define ID_VIEW_CHATBAR                 32953
#define ID_VIEW_GAMEBAR                 32954
#define ID_GAMECQ_CHANGEUSERNAME        32957
#define ID_GAMECQ_CHANGEEMAIL           32958
#define ID_PLAYER_KICK                  32959
#define ID_GAME_KICK                    32960
#define ID_GAME_BAN                     32961
#define ID_VIEW_IGNORES                 32962
#define ID_ADMIN_WEB                    32963
#define ID_VIEW_CHATOUTPUT              32964
#define ID_ADMIN_SERVERS                32965
#define ID_PROCESS_EDIT                 32966
#define ID_PROCESS_CONFIGURE            32967
#define ID_PROCESS_LOG                  32968
#define ID_PROCESS_START                32969
#define ID_PROCESS_STOP                 32970
#define ID_PROCESS_RESTART              32971
#define ID_PROCESS_DELETE               32972
#define ID_SERVER_ADDPROCESS            32973
#define ID_SERVER_STARTALL              32974
#define ID_SERVER_STOPALL               32975
#define ID_SERVER_RESTARTALL            32976
#define ID_SERVER_REBOOT                32977
#define ID_SERVER_RESTART               32978
#define ID_SERVER_LOG                   32980
#define ID_SERVER_CONFIGURE             32982
#define ID_SERVER_SHUTDOWN              32983
#define ID_SERVER_REFRESH               32984
#define ID_ADMIN_USERS                  32985
#define ID_EDIT_FINDUSERS               32986
#define ID_GAMECQ_STOPCHATLOG           32987
#define ID_GAMEBAR_UPDATE               32988
#define ID_GAMEBAR_NEWS                 32989
#define ID_NAVBAR_NEWS                  32990
#define ID_NAVBAR_HOME                  32991
#define ID_NAVBAR_FORUM                 32992
#define ID_GAMEBAR_TUTORIAL             32993
#define ID_GAMEBAR_SETUP                32994
#define ID_NAVBAR_DOWNLOADS             32995
#define ID_PLAYER_MUTE                  32996
#define ID_PLAYER_UNMUTE                32997
#define ID_MANAGE_USERS                 33000
#define ID_POSTING_SET                  33001
#define ID_POSTING_VIEW                 33002
#define ID_PROCESS_TERMINATE            33003
#define ID_ADMIN_WATCHLIST              33004
#define ID_CHAT_HIDE                    33006
#define ID_GAMECQ_SAVECHAT_AS           33007
#define ID_PLAYER_CLONES                33008
#define ID_PLAYER_CHECK                 33009
#define ID_GAMEBAR_STAFF                33010
#define ID_CHAT_CREATEROOM              33022
#define ID_GAMECQ_CHAT                  33023
#define ID_GAMECQ_GAMES                 33024
#define ID_GAMECQ_SERVERS               33025
#define ID_GAMECQ_NEWS                  33026
#define ID_GAMECQ_BROWSE                33029
#define ID_GAMECQ_HOME33030             33030
#define ID_GAMECQ_BROWSE33031           33031
#define ID_NAVBAR_PROFILE               33033
#define ID_GAMECQ_CHANGEPASSWORD        33034
#define ID_SERVER_CONNECT               33035
#define ID_SERVER_KICK                  33037
#define ID_SERVER_BAN                   33038
#define ID_GAMES_INSTALL                33039
#define ID_GAMES_UNINSTALL              33040
#define ID_GAMES_LAUNCH                 33041
#define ID_GAMES_PROPERTIES             33042
#define ID_GAMES_DELETE                 33043
#define ID_VIEW_HOME                    33044
#define ID_VIEW_CHAT                    33045
#define ID_VIEW_GAMES                   33046
#define ID_VIEW_SERVERS                 33047
#define ID_GAMES_UPDATE                 33048
#define ID_SERVER_FILTER                33049
#define ID_FILTER_GAME                  33050
#define ID_FILTER_PING                  33051
#define ID_PLAYER_MODSEND               33055
#define ID_PLAYER_SESSION               33057
#define ID_HELP_SUPPORTONLINE           33059
#define ID_HELP_FAQ                     33060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         33061
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
